my_project/app/urls.py
from django.urls import path
from .views import ProductView, ListProductsView

app_name = 'app'

urlpatterns = [
    path('products/', ProductView.as_view(), name='product'),
    path('products/list/', ListProductsView.as_view(), name='product_list'),
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

my_project/app/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

my_project/app/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Product
# Create your views here.

class ProductView(View):
    def get(self, request):
        return render(request, 'products.html')
    
    def post(self, request):
        name = request.POST.get('name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        
        product = Product(name=name, description=description, price=price)
        product.save()
        
        return redirect('app:product_list')
    
class ListProductsView(View):
    def get(self, request):
        products = Product.objects.all()
        return render(request, 'product_list.html', {'products': products})

my_project/app/templates/product_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Proyecto</title>
</head>
<body>
    {% if products %}
        <h1>Lista de Productos</h1>
        <ul>
            {% for product in products %}
                <li>{{ product.name }} - {{ product.price }} $ - {{ product.description }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h1>No hay productos disponibles.</h1>
    {% endif %}
</body>
</html>

my_project/app/templates/products.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Proyecto</title>
</head>
<body>
    <form action="{% url 'app:product' %}" method="post">
        {% csrf_token %}
        <h1>Agregar Producto</h1>
        <label for="name">Nombre del Producto:</label>
        <input type="text" id="name" name="name" required>
        <br>
        <label for="description">Descripción:</label>
        <textarea id="description" name="description" required></textarea>
        <br>
        <label for="price">Precio:</label>
        <input type="number" id="price" name="price" step="0.01" required>
        <br>
        <button type="submit">Agregar Producto</button>
    </form>

    TMRE
</body>
</html>